### ISSUE TITLE
Hardcoded to ~/Sites directory

### ISSUE THREAD

**Issue by vitch** [stevegrunwell/asimov#10]
Thanks for this script - I found it while waiting days for my first time machine backup to process!

It seems to work well but is hardcoded to look in `~/Sites`. My code lives in `~/Code`... I edited the script but it would be nice if this was in some way configurable...

**Comment by stevegrunwell** [comment]
@vitch That's a great catch of something left over from testing, thank you!

I just merged #11, which changes this to the current user's home directory. You just saved me a whole bunch of space on my Time Machine disk, as directories within `~/Vagrant/VVV` are now being blocked on my machine, so thank you!!
