### ISSUE TITLE
Why not using the -p flag?

### ISSUE THREAD

**Issue by muuvmuuv** [stevegrunwell/asimov#23]
https://github.com/stevegrunwell/asimov/blob/f3075ec7bd62c29a76d2a0ebfbce24477de44885/asimov#L51

Why don‘t you add the `-p` flag, so it will not be sticky?

**Comment by rowanbeentje** [comment]
What's the advantage of non-sticky exclusions?  Is it because then deleting/recreating is still excluded, even if folder moves etc aren't?

(One big disadvantage is that `-p` needs root privileges!)

**Comment by muuvmuuv** [comment]
Ah okay that would break the simplyness. Didn‘t saw that. Yes that was my advantage. Maybe we can add options in the future to implement this or other options? Like specify a path to search through (that would then be a new issue ^^)
