### ISSUE TITLE
Does it work with .git directories?

### ISSUE THREAD

**Issue by corradomatt** [stevegrunwell/asimov#24]
This looks very interesting...can it be setup to exclude `.git` directories as well?

**Comment by muuvmuuv** [comment]
I think you could easily edit those line https://github.com/stevegrunwell/asimov/blob/develop/asimov#L19-L24 and add GIT. Just try it out :)

**Comment by stevegrunwell** [comment]
It would be easy to omit Git directories, but that feels counter-productive; the goal of Asimov is to prevent the backup of easily-recreated items like third-party npm and Composer packages.

Considering not all Git repos are stored remotely (or aren't always up-to-date), blocking `.git` directories could cause Asimov to prevent backups of important work, not just third-party dependencies that are easily restored.

If you'd like to explicitly block `.git` directories, you may explicitly call `tmutil addexclusion <path>` to block the directory from being backed up to Time Machine.
