### ISSUE TITLE
Read .gitignore files

### ISSUE THREAD

**Issue by olso** [stevegrunwell/asimov#42]
Lot of people have their `.gitignore` setup which already removes files

Maybe it could solve something like https://stackoverflow.com/questions/50788796/how-to-exclude-or-use-global-gitignore-file-and-directories-from-timemachine-ba

Just ran into this, might even PR

**Comment by tdhulster** [comment]
https://github.com/samuelmeuli/tmignore does that

**Comment by stevegrunwell** [comment]
> **Disclosure:** This issue was the first time I had heard of tmignore, and while I haven't used that tool, I'm thrilled to see developers across the globe being proactive about keeping their backups lean 😁 

The `.gitignore` file may be designed to keep certain files out of a repository, but that doesn't always mean they should be excluded from backups.

For example: my project's local configuration file does **not** belong in source control, but it would be a bummer if my system crashed and I had to recover from Time Machine _and_ rebuild the configuration file.

[It appears that tmignore does permit certain file/directory patterns to be explicitly included in the Time Machine backups](https://github.com/samuelmeuli/tmignore#configuration), but I think the two projects are approaching it from two different positions: while tmignore tries to squeeze every last unneeded file out of the Time Machine backups, Asimov takes more of a "we'll keep out the things that we are **certain** can easily be re-installed if needed" approach. The latter might result in some unnecessary files getting into the backups, but it also means you won't risk important files **not** getting in.

Fortunately, tools are using tmutil under the hood, though, so they _should_ work just fine together if you want maximum exclusions 😄.

Thank you for the suggestion, and please give us a heads up if you do happen to run into conflicts when using both!
