### ISSUE TITLE
Wanted: Co-Maintainer

### ISSUE THREAD

**Issue by stevegrunwell** [stevegrunwell/asimov#48]
Asimov has received a lot of attention, but I haven't had much time as-of-late to dedicate to the project.

If there's another developer out there (preferably with experience writing performant bash scripts) that would like to volunteer to join me in maintaining this project, please get in touch!

**Comment by sudar** [comment]
Hello @stevegrunwell 

How are you? Long time no see :)

I have been using asimov for more than a year and would like to volunteer and give you a helping hand in maintaining this project.

Let me know how I could be of help.

**Comment by stevegrunwell** [comment]
@sudar, you're the best!!

Lemme work on writing down all of the disparate thoughts I've had (which vaguely resemble a roadmap). In the meantime, commit access is coming your way!

Can't wait to work with you again! 😁
