### ISSUE TITLE
Feature request: add `venv requirements.txt`

### ISSUE THREAD

**Issue by huyz** [stevegrunwell/asimov#63]
It's very common for people to create a `venv` or `.venv` folder, using `virtualenv` or `python -m venv`, alongside the  `requirements.txt` file for Python
```
    'venv requirements.txt'       # virtualenv (python)
    '.venv requirements.txt'      # virtualenv (python)
```

**Comment by akermen** [comment]
also '.virtualenv' and 'virtualenv' folders and not just 'requirements.txt' but 'requirements.*.txt (requirements.test.txt, requirements.prod.txt)

**Comment by huyz** [comment]
Too bad there isn't a consensus on naming.  So this message here is purely my opinion.

I think that `.virtualenv` and `virtualenv` are not common.  I have never seen these.

If you want to see a list of common ones, take a look at https://github.com/github/gitignore/blob/master/Python.gitignore :
```
.env
.venv
env/
venv/
ENV/
```

Also, I've seen `requirements-*.txt` and never `requirements.*.txt`

In any case, we probably need some sort of configuration file.

**Comment by djay** [comment]
There is a pyvenv.cfg file created - https://docs.python.org/3/library/venv.html

There will also be a lib/python*/site-packages/*.[dist-info|egg-info]. I'm not sure if there is a way to differentiate between this and global site-packages however.
