### ISSUE TITLE
Symlinked path doesn't point to correct location

### ISSUE THREAD

**Issue by morganestes** [stevegrunwell/asimov#7]
When I run `install.sh`, the directory gets declared as `.`, resulting in a symlink path of `./asimov`  inside `/usr/local/bin`. This causes the script to fail as it can't find the correct path of the executable inside the repo.

Changing to `$(pwd)` inside the installer fixes this, so the symlink points to the full path and not the relative one.

**Comment by stevegrunwell** [comment]
Morgan, as usual:

1. Thanks for the detailed bug report and pull request; you're always one of the first to try out my latest projects and let me know when things don't go as planned.
2. Sorry this has been hanging out there for over a week, despite being a one-line change.

Happy Thanksgiving! 🦃

**Comment by morganestes** [comment]
Thanks for creating and sharing some great tools! No worries about timing, it's yours to do with as you see fit, and mine to use and suggest. :smiling:
